'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3615
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''IC_NumberTwo class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class IC_NumberTwo

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lbPageTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbPageTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbPrompt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbPrompt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txData As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btVerifyFinished control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btVerifyFinished As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbWSCData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbWSCData As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbWSC_Desc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbWSC_Desc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbLot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbLot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbLotData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbLotData As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbPounds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbPounds As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbPoundsData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbPoundsData As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbFunction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbFunction As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btReturn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btReturn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btRestart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btRestart As Global.System.Web.UI.WebControls.Button
End Class
