'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class IC_ShippingPalletsNew

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lbPageTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbPageTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbUser As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbPrompt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbPrompt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btNew As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btComplete As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btNo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btYes As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbShipPallet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbShipPallet As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbShipPalletValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbShipPalletValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbOrder As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''htxOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents htxOrder As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lbProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbProduct As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''htxProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents htxProduct As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lbCaseLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCaseLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''htxPallet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents htxPallet As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lbQuantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbQuantity As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txQuantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txQuantity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbQtyRemain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbQtyRemain As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbGrossWt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbGrossWt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txGrossWt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txGrossWt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbDatePackaged control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDatePackaged As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txDatePackaged control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txDatePackaged As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbBin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbBin As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txBin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txBin As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbComplete As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbPrinter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbPrinter As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txPrinter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txPrinter As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btReturn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btReturn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btRestart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btRestart As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbGridTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbGridTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dgProductsScanned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgProductsScanned As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''lbExistingGridTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbExistingGridTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dgExistingProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgExistingProducts As Global.System.Web.UI.WebControls.DataGrid
End Class
